:: ** This file was automatically generated by generate_buildscripts.sh **
SET MSBUILD_PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin;C:\Program Files\CMake\bin
SET PATH=%PATH%;%MSBUILD_PATH%
choco install wget
choco install 7zip
choco install cmake
python --version
echo "available python version must be greater than 2.7.13 or pip install certifi"
git clone https://github.com/emscripten-core/emsdk.git
cd emsdk
call emsdk.bat install latest
call emsdk.bat activate latest
cd ..
choco install vcbuildtools -ia "/InstallSelectableItems Win81SDK_CppBuildSKUV1;VisualCppBuildTools_ATLMFC_SDK"
SET PATH=%PATH%;%MSBUILD_PATH%
cd oactobjs32
wget -q "https://dl.bintray.com/boostorg/release/1.64.0/source/boost_1_64_0.zip"
7z x -bd boost_1_64_0.zip
cd boost_1_64_0
call bootstrap.bat
./b2.exe toolset=msvc-14.0 link=static address-model=32 architecture=x86 runtime-link=static threading=multi --layout=versioned --with-date_time
SET BOOST_INCL="%cd%"
SET BOOST_LIB="%cd%\stage\lib"
cd ../..
cd anypiab
mkdir build
cd build
call emcmake cmake -DBOOST_ROOT=%BOOST_INCL% -DBOOST_LIBRARYDIR=%BOOST_LIB%  -G "NMake Makefiles" ..
nmake
