:: ** This file was automatically generated by generate_buildscripts.sh **
SET MSBUILD_PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin;C:\Program Files\CMake\bin
SET PATH=%PATH%;%MSBUILD_PATH%
python --version
echo "available python version must be greater than 2.7.13 or pip install certifi"

cd emsdk
call emsdk_env.bat install latest
call emsdk_env.bat activate latest
cd ..

export PATH=$MSBUILD_PATH:$PATH
cd oactobjs32


cd boost_1_64_0


export BOOST_INCL="`pwd`"
export BOOST_LIB="`pwd`\stage\lib"
cd ../..
cd anypiab
mkdir build
cd build
../../emsdk/upstream/emscripten/emcmake cmake -DBOOST_ROOT=$BOOST_INCL -DBOOST_LIBRARYDIR=$BOOST_LIB -G "NMake Makefiles" ..
nmake
cd ../..
mkdir anypiajs/build
cd anypiajs/build
../../emsdk/upstream/emscripten/emcmake cmake -DBOOST_ROOT=$BOOST_INCL -DBOOST_LIBRARYDIR=$BOOST_LIB -G "NMake Makefiles" ..
nmake
